"""
Dati di arricchimento del catalogo LANCER, scritti a mano (non generati
da un LLM a runtime): nome tecnico italiano, categoria, funzione,
sinonimi colloquiali e termini siciliani.

Struttura:
  CONCETTI  id -> (nome_it, categoria, funzione, sinonimi, siciliano)
            sinonimi/siciliano: stringhe separate da ';'
  REGOLE    lista ordinata (regex sul "tipo" normalizzato, id concetto):
            vince la PRIMA che corrisponde, quindi le regole piu'
            specifiche stanno sopra quelle generiche.

Il "tipo" e' la descrizione inglese del PDF senza misure/modelli (vedi
arricchisci.tipo_di): "Hex Bolt M12 x 35 8.8 Zn D933" -> "hex bolt".
Destro/sinistro (LH/RH) NON sta qui: viene ricavato dalla descrizione
originale in arricchisci.py.

Il siciliano e' volutamente prudente (solo forme d'uso comune) ed e'
DA VERIFICARE con l'azienda: e' la parte piu' incerta.

Per aggiungere un termine: modificare il concetto qui e rilanciare
  ./venv/Scripts/python.exe lancer_db/arricchisci.py
"""

# categorie (elenco chiuso, usato anche come filtro di ricerca)
TEL = "Telaio e carpenteria"
ROT = "Rotore e utensili di lavoro"
TRA = "Trasmissione e scatola ingranaggi"
CUS = "Cuscinetti, tenute e guarnizioni"
BUL = "Bulloneria e minuteria"
RUL = "Rulli e ruote"
IDR = "Impianto idraulico"
PRO = "Protezioni, cofani e carter"
ATT = "Attacco tre punti, slitte e regolazioni"
CIN = "Cinghie e pulegge"
LUB = "Lubrificazione, tappi e sfiati"
ALT = "Altro"

CATEGORIE = [TEL, ROT, TRA, CUS, BUL, RUL, IDR, PRO, ATT, CIN, LUB, ALT]

CONCETTI = {
    # ------------------------------------------------------------ bulloneria
    "bullone": ("bullone a testa esagonale", BUL,
                "vite a testa esagonale con dado, fissa le parti del telaio e dei gruppi",
                "bullone; vite; bullone esagonale; vite testa esagonale; bullone con dado; perno filettato",
                "bulluni; viti"),
    "bullone_carrozzeria": ("bullone a testa tonda con quadro sottotesta", BUL,
                "bullone a testa bombata con collo quadro, non gira mentre si stringe il dado",
                "bullone testa tonda; bullone a fungo; bullone carrozzeria; bullone con il quadro; vite testa tonda",
                "bulluni"),
    "bullone_forato": ("bullone forato (banjo)", IDR,
                "bullone cavo che fissa il raccordo a occhio di un tubo idraulico lasciando passare l'olio",
                "bullone banjo; bullone forato; vite forata; bullone del tubo dell'olio; raccordo a occhio",
                ""),
    "vite_svasata": ("vite a testa svasata con esagono incassato", BUL,
                "vite a brugola a testa piana che rimane a filo della superficie",
                "vite a brugola; brugola svasata; vite svasata; vite a testa piatta; vite con la brugola",
                "viti"),
    "vite_brugola": ("vite a testa cilindrica con esagono incassato", BUL,
                "vite a brugola a testa cilindrica",
                "vite a brugola; brugola; vite testa cilindrica; vite con la brugola",
                "viti"),
    "maniglia": ("maniglia con vite di serraggio", ALT,
                "manopola/maniglia a vite per bloccare una regolazione a mano",
                "maniglia; pomello; manopola; vite a farfalla; volantino di serraggio",
                ""),
    "cavallotto": ("cavallotto a U (bullone a U)", BUL,
                "bullone piegato a U che fissa staffe e protezioni a un tubo quadro o tondo",
                "cavallotto; bullone a U; staffa a U; cavaliere; ferro a U filettato",
                "cavaddottu"),
    "dado_autobloccante": ("dado autobloccante", BUL,
                "dado con anello in nylon che non si svita con le vibrazioni",
                "dado; dado autobloccante; dado con la plastica; dado con il nylon; dado antisvitamento; dado bloccante",
                "dadu"),
    "dado": ("dado esagonale", BUL,
                "dado normale per bulloni",
                "dado; dado esagonale; dado normale; bullone femmina",
                "dadu"),
    "ghiera": ("ghiera autobloccante", BUL,
                "ghiera tonda filettata con inserto in nylon che blocca un albero o un cuscinetto",
                "ghiera; dado tondo; ghiera del mozzo; dado a intagli; ghiera con la plastica",
                ""),
    "dado_corona": ("dado a intagli (dado a corona)", BUL,
                "dado grosso ad intagli bloccato con coppiglia, tiene in posizione ingranaggi e mozzi",
                "dado a corona; dado a castello; dado con la coppiglia; ghiera; dado grosso dell'ingranaggio",
                "dadu"),
    "rondella_grower": ("rondella elastica (grower)", BUL,
                "rondella spaccata elastica che impedisce al bullone di allentarsi",
                "grower; rondella grower; rondella spaccata; rondella elastica; rondella a molla",
                "rundedda; rudedda"),
    "rondella": ("rondella piana", BUL,
                "rondella piatta sotto dado o testa del bullone",
                "rondella; rondella piana; ranella; spessore; anello piatto",
                "rundedda; rudedda"),
    "spina_scatto": ("spina a scatto con anello (linch pin)", BUL,
                "spina con anello ribaltabile che blocca i perni dell'attacco a tre punti",
                "spina a scatto; spina con anello; copiglia ad anello; spina di sicurezza; fermo del perno; copiglia a scatto",
                "cupigghia"),
    "copiglia_r": ("copiglia a R (molletta)", BUL,
                "molletta elastica a forma di R che blocca perni e spine",
                "copiglia a R; molletta; forcella; spinetta a molla; copiglia elastica",
                "cupigghia"),
    "coppiglia": ("coppiglia", BUL,
                "filo piegato che si infila nel foro del perno o del dado a corona e si apre",
                "coppiglia; copiglia; spinotto aperto; coppiglia spaccata",
                "cupigghia"),
    "spina_elastica": ("spina elastica", BUL,
                "spina cilindrica spaccata piantata a pressione per bloccare due pezzi",
                "spina elastica; spina; spinotto; spina a molla; perno elastico",
                ""),
    "spina_fermo": ("spina di fermo", BUL,
                "spina che blocca un supporto o il gancio del cardano",
                "spina; perno di fermo; spinotto; spina del cardano",
                "pernu"),
    "perno_attacco": ("perno attacco tre punti", ATT,
                "perno su cui si agganciano i bracci inferiori del sollevatore del trattore",
                "perno; perno di attacco; perno dei bracci; perno del sollevatore; spinotto del tre punti",
                "pernu"),
    "perno": ("perno", BUL,
                "perno cilindrico di articolazione o di attacco",
                "perno; spinotto; spina; asse; perno di snodo",
                "pernu"),
    "perno_cerniera": ("perno cerniera", BUL,
                "perno su cui ruota una parte incernierata (bracci pieghevoli)",
                "perno cerniera; perno di snodo; perno del braccio; spinotto",
                "pernu"),
    "rivetto": ("rivetto", BUL, "rivetto in acciaio per fissaggi non smontabili",
                "rivetto; ribattino; chiodo da ribattere", ""),
    "linguetta": ("linguetta", TRA,
                "chiavetta che rende solidale un ingranaggio o una puleggia all'albero",
                "linguetta; chiavetta; chiavella; chiave dell'albero; tassello",
                "chiavetta"),
    "tappo_tubo": ("tappo di chiusura per tubo", ALT,
                "tappo in plastica che chiude l'estremita' dei tubi del telaio",
                "tappo; tappo di plastica; tappo del tubo; copritubo; tappino",
                "tappu"),
    "distanziale": ("distanziale", BUL,
                "spessore o bussola che tiene la giusta distanza tra due pezzi",
                "distanziale; spessore; distanziatore; bussola; anello distanziale; tubetto",
                ""),
    "boccola": ("boccola", CUS,
                "bussola di scorrimento (in bronzo, acciaio o teflon) su cui gira o scorre un perno",
                "boccola; bronzina; bussola; boccola in teflon; manicotto",
                "buccula"),
    "spessori": ("kit spessori (rasamenti)", TRA,
                "anelli calibrati sottili per registrare il gioco di ingranaggi e cuscinetti",
                "spessori; rasamenti; lamierini; anellini di spessore; shim",
                ""),
    "calettatore": ("calettatore (bussola di serraggio)", TRA,
                "bussola conica che blocca la puleggia sull'albero senza linguetta",
                "calettatore; sit lock; bussola di serraggio; bussola conica; blocca puleggia",
                ""),
    "portadocumenti": ("porta libretto", ALT,
                "tubo/scatola che contiene il manuale d'uso sulla macchina",
                "porta manuale; porta libretto; tubo dei documenti; scatola del libretto",
                ""),
    "piastra": ("piastra", TEL,
                "piastra di supporto o di copertura del telaio",
                "piastra; lamiera; piastra di supporto; piatto di ferro",
                "chiastra"),

    # --------------------------------------------------- cuscinetti e tenute
    "cuscinetto_conico": ("cuscinetto a rulli conici", CUS,
                "cuscinetto che regge carichi radiali e assiali, su alberi della scatola ingranaggi e mozzi",
                "cuscinetto; cuscinetto conico; cuscinetto a rulli; rullini; cuscinetto della scatola; cuscinetto del mozzo",
                "cuscinettu"),
    "cuscinetto_sfere": ("cuscinetto radiale a sfere", CUS,
                "cuscinetto a sfere per alberi e rulli",
                "cuscinetto; cuscinetto a sfere; cuscinetto a palline; cuscinetto del rullo",
                "cuscinettu"),
    "cuscinetto_orientabile": ("cuscinetto orientabile a rulli", CUS,
                "cuscinetto a doppia fila di rulli che tollera disallineamenti, sul rotore della trinciatrice",
                "cuscinetto; cuscinetto orientabile; cuscinetto a botte; cuscinetto del rotore; cuscinetto grosso",
                "cuscinettu"),
    "supporto_flangiato": ("supporto flangiato con cuscinetto (UCF)", CUS,
                "supporto in ghisa a flangia quadra con cuscinetto, regge l'albero del rullo",
                "supporto; supporto con cuscinetto; supporto del rullo; supporto flangiato; cuscinetto con flangia; testata del rullo",
                "cuscinettu"),
    "mozzo_disco": ("mozzo con cuscinetto per disco (agri hub)", CUS,
                "mozzo sigillato con cuscinetto su cui e' imbullonato il disco dell'erpice",
                "mozzo; mozzo del disco; cuscinetto del disco; agri hub; mozzo con cuscinetto",
                "cuscinettu"),
    "paraolio": ("anello di tenuta (paraolio)", CUS,
                "anello in gomma con molla che impedisce all'olio di uscire lungo un albero",
                "paraolio; anello paraolio; guarnizione dell'olio; tenuta dell'albero; paraolio della scatola",
                "paraogghiu"),
    "oring": ("anello OR (O-ring)", CUS,
                "guarnizione ad anello in gomma a sezione tonda",
                "OR; o-ring; anello di gomma; guarnizione tonda; anellino di gomma",
                "aneddu di gomma"),
    "tenuta_meccanica": ("tenuta meccanica frontale (duo-cone)", CUS,
                "coppia di anelli metallici con OR che sigilla il mozzo del rotore contro terra e acqua",
                "tenuta meccanica; tenuta frontale; duo cone; anelli di tenuta del mozzo; tenuta a specchio",
                ""),
    "tappo_cieco": ("tappo di tenuta cieco", CUS,
                "coperchietto metallo-gomma che chiude a tenuta un foro della scatola",
                "tappo cieco; coperchietto; tappo di tenuta; paraolio cieco",
                "tappu"),
    "raschiastelo": ("guarnizione raschiatore", CUS,
                "guarnizione che pulisce il tubo scorrevole dallo sporco",
                "raschiatore; guarnizione raschiastelo; parapolvere; guarnizione del tubo",
                ""),
    "rondella_dowty": ("rondella di tenuta (dowty)", IDR,
                "rondella metallo-gomma che fa tenuta sui raccordi idraulici",
                "rondella di tenuta; dowty; rondella del raccordo; guarnizione del raccordo; rondella in gomma",
                "rundedda"),
    "guarnizione": ("guarnizione piana", CUS,
                "guarnizione (carta o fibra) tra coperchio e corpo della scatola o del carter",
                "guarnizione; guarnizione di carta; guarnizione del coperchio; guarnizione piana",
                "uarnizioni"),
    "seeger_interno": ("anello elastico per fori (seeger interno)", BUL,
                "anello elastico che blocca un cuscinetto dentro la sua sede",
                "seeger; seeger interno; anello elastico; anello di fermo; molletta del cuscinetto",
                ""),
    "seeger_esterno": ("anello elastico per alberi (seeger esterno)", BUL,
                "anello elastico che blocca un cuscinetto o un ingranaggio sull'albero",
                "seeger; seeger esterno; anello elastico; anello di fermo; fermo dell'albero",
                ""),

    # ------------------------------------------------------- lubrificazione
    "ingrassatore": ("ingrassatore", LUB,
                "valvolina dove si attacca la pompa del grasso",
                "ingrassatore; nipplo; nipplo del grasso; ingrassatore a 45 gradi; punto di ingrassaggio",
                "ngrassaturi"),
    "prolunga_ingrassatore": ("prolunga ingrassatore", LUB,
                "prolunga che porta l'ingrassatore in posizione raggiungibile",
                "prolunga ingrassatore; tubetto del grasso; ingrassatore lungo",
                ""),
    "tappo_sfiato": ("tappo di sfiato", LUB,
                "tappo con sfiato che fa respirare la scatola ingranaggi",
                "sfiato; tappo sfiato; tappo di carico olio; tappo con il buco; respiro della scatola",
                "tappu"),
    "spia_livello": ("indicatore livello olio", LUB,
                "tappo con vetrino o astina per controllare il livello dell'olio",
                "spia olio; livello olio; tappo livello; oblo' dell'olio; astina",
                ""),
    "tappo_olio": ("tappo filettato", LUB,
                "tappo di carico o scarico olio della scatola",
                "tappo; tappo dell'olio; tappo di scarico; tappo di carico; tappo filettato",
                "tappu"),
    "coppa_mozzo": ("coppa lato supporto", LUB,
                "coperchio a coppa sul mozzo del rotore dal lato opposto alla trasmissione",
                "coppa; coperchio del mozzo; tazza; coppa del grasso; coperchio lato supporto",
                ""),

    # -------------------------------------------------------- idraulica
    "cilindro_idraulico": ("cilindro idraulico", IDR,
                "attuatore a olio che sposta o solleva una parte (spostamento laterale, rullo, bracci)",
                "pistone; pistone idraulico; martinetto; cilindro; cilindro dell'olio; pistone che alza; pompante",
                "pistuni"),
    "pistoncino": ("pistoncino di bloccaggio", ATT,
                "piccolo pistone/nottolino che blocca in posizione un elemento scorrevole",
                "pistoncino; nottolino; fermo; puntalino; pernino a molla",
                ""),
    "tubo_idraulico": ("tubo idraulico flessibile", IDR,
                "tubo in gomma ad alta pressione con raccordi che porta l'olio dal trattore al cilindro",
                "tubo dell'olio; tubo idraulico; flessibile; tubo in gomma; tubo alta pressione; manichetta",
                "tubbu"),
    "innesto_rapido": ("innesto rapido maschio", IDR,
                "attacco rapido che si inserisce nelle prese idrauliche del trattore",
                "attacco rapido; innesto rapido; innesto dell'olio; spina dell'olio; maschio dell'attacco",
                ""),
    "raccordo": ("raccordo idraulico maschio", IDR,
                "raccordo filettato per collegare tubi e cilindri",
                "raccordo; nipplo; raccordo maschio; attacco del tubo; riduzione",
                ""),
    "raccordo_t": ("raccordo a T", IDR,
                "raccordo a tre vie per dividere la linea idraulica",
                "raccordo a T; T dell'olio; derivazione; tre vie",
                ""),
    "divisore_flusso": ("divisore di flusso", IDR,
                "valvola che divide l'olio in parti uguali tra due cilindri per farli muovere insieme",
                "divisore di flusso; ripartitore; valvola divisore; divisore dell'olio",
                ""),
    "fascetta_tubi": ("morsetto doppio per tubi", IDR,
                "morsetto che tiene fermi due tubi idraulici affiancati",
                "fascetta; morsetto dei tubi; collare; ferma tubi",
                ""),

    # ------------------------------------------------------- trasmissione
    "rinvio_prolunga": ("gruppo rinvio con prolunga (trinciatrice)", TRA,
                "scatola ingranaggi della trinciatrice con albero di prolunga verso la puleggia",
                "rinvio; scatola del rinvio; gruppo ingranaggi; scatola della trincia; moltiplicatore; centralina",
                ""),
    "scatola_ingranaggi": ("scatola ingranaggi (gruppo completo)", TRA,
                "gruppo che riceve il moto dal cardano e lo manda al rotore",
                "scatola ingranaggi; scatola del cambio; rinvio; cambio; gruppo conico; centralina; scatola della fresa",
                "scatula"),
    "corpo_scatola": ("corpo scatola ingranaggi", TRA,
                "carcassa in ghisa della scatola ingranaggi",
                "corpo della scatola; carcassa; scatola vuota; cassa del cambio; corpo del rinvio",
                "scatula"),
    "coperchio_scatola": ("coperchio scatola ingranaggi", TRA,
                "coperchio imbullonato che chiude la scatola ingranaggi",
                "coperchio; coperchio della scatola; tappo della scatola; coperchio del cambio; piastra di chiusura",
                ""),
    "coperchio_cascata": ("coperchio carter ingranaggi laterale", TRA,
                "coperchio del carter laterale dove girano gli ingranaggi a cascata",
                "coperchio laterale; coperchio della cascata; coperchio ingranaggi; coperchio del carter",
                ""),
    "supporto_scatola": ("supporto scatola ingranaggi", TEL,
                "staffa o tubo che sostiene la scatola ingranaggi sul telaio",
                "supporto della scatola; staffa della scatola; supporto del cambio; tubo di supporto; fascetta della scatola",
                ""),
    "carter_laterale": ("carter trasmissione laterale", TRA,
                "carter sul fianco della fresa che contiene gli ingranaggi (o la catena) che portano il moto al rotore",
                "carter laterale; cascata; scatola laterale; trasmissione laterale; carter degli ingranaggi; fianco con gli ingranaggi",
                ""),
    "trasmissione_laterale": ("gruppo trasmissione laterale", TRA,
                "gruppo completo della trasmissione laterale (carter + ingranaggi)",
                "trasmissione laterale; cascata completa; carter laterale completo",
                ""),
    "albero_trasmissione": ("albero di trasmissione laterale", TRA,
                "albero lungo (nel suo tubo) che porta il moto dalla scatola centrale al carter laterale",
                "albero; albero di trasmissione; albero lungo; barra; asse; tubo con l'albero dentro",
                "arvulu"),
    "albero_entrata": ("albero di entrata (presa di forza)", TRA,
                "albero scanalato su cui si innesta il cardano",
                "albero entrata; albero scanalato; albero del cardano; albero presa di forza; codolo",
                "arvulu"),
    "albero_portalama": ("albero portalama", ROT,
                "albero verticale su cui e' montato il mozzo con le lame del rasaerba",
                "albero delle lame; albero portalama; asse della lama",
                "arvulu"),
    "albero_intermedio": ("albero intermedio", TRA,
                "albero interno della scatola ingranaggi",
                "albero intermedio; alberino; albero della scatola",
                "arvulu"),
    "pignone_conico": ("pignone conico", TRA,
                "ingranaggio conico piccolo (spesso con albero) della coppia conica",
                "pignone; pignone conico; coppia conica; ingranaggio piccolo; albero pignone",
                ""),
    "corona_conica": ("corona conica", TRA,
                "ingranaggio conico grande della coppia conica",
                "corona; corona conica; coppia conica; ingranaggio grande; ingranaggio conico",
                ""),
    "ingranaggio_cascata": ("ingranaggio trasmissione laterale", TRA,
                "ingranaggio dritto della cascata laterale (superiore, intermedio o inferiore)",
                "ingranaggio; ruota dentata; pignone; ingranaggio della cascata; dentata",
                ""),
    "ingranaggio_cambio": ("ingranaggio del cambio velocita'", TRA,
                "ingranaggi intercambiabili che cambiano la velocita' del rotore",
                "ingranaggio; coppia di ingranaggi; cambio velocita'; ingranaggi di ricambio; rapporto",
                ""),
    "flangia_ingranaggio": ("flangia ingranaggio centrale", TRA,
                "flangia che sostiene l'ingranaggio intermedio della cascata",
                "flangia; flangia dell'ingranaggio; supporto ingranaggio",
                ""),
    "perno_ingranaggio": ("perno ingranaggio intermedio", TRA,
                "perno su cui gira l'ingranaggio intermedio della cascata",
                "perno; perno dell'ingranaggio; asse dell'ingranaggio",
                "pernu"),
    "mozzo_rotore": ("mozzo rotore (gruppo)", TRA,
                "gruppo mozzo alle estremita' del rotore, con cuscinetti e tenute",
                "mozzo; mozzo del rotore; testata del rotore; supporto del rotore; mozzo completo",
                ""),
    "supporto_mozzo": ("supporto mozzo rotore", TRA,
                "alloggiamento dei cuscinetti del mozzo del rotore",
                "supporto mozzo; sede dei cuscinetti; porta cuscinetto; campana del mozzo",
                ""),
    "albero_mozzo": ("albero mozzo rotore", TRA,
                "albero corto del mozzo su cui si imbullona il rotore",
                "albero del mozzo; perno del rotore; alberino del mozzo",
                "arvulu"),
    "parapolvere": ("parapolvere", CUS,
                "disco/coperchio che protegge le tenute del mozzo da terra ed erba",
                "parapolvere; coperchio antipolvere; protezione del mozzo; lamierino del mozzo",
                ""),
    "giunto": ("giunto", TRA, "giunto di collegamento tra due alberi",
                "giunto; manicotto; accoppiamento", ""),
    "puleggia": ("puleggia", CIN,
                "ruota a gole per cinghie trapezoidali",
                "puleggia; carrucola; ruota della cinghia; puleggia della trincia",
                ""),
    "cinghia": ("cinghia trapezoidale", CIN,
                "cinghia che trasmette il moto dalla puleggia al rotore",
                "cinghia; cinghie; cinghia trapezoidale; cinghia della trincia; correa",
                "cìnghia"),
    "tendicinghia": ("piastra tendicinghia", CIN,
                "piastra di regolazione per tendere le cinghie",
                "tendicinghia; tenditore; piastra del tenditore",
                ""),
    "protezione_cardano": ("protezione cardano", PRO,
                "cuffia che copre l'albero cardanico all'attacco della macchina",
                "protezione cardano; cuffia; cuffia del cardano; protezione presa di forza; campana",
                ""),
    "supporto_cardano": ("supporto appoggia-cardano", ATT,
                "gancio o asta su cui appoggiare il cardano quando la macchina e' staccata",
                "gancio del cardano; appoggia cardano; supporto cardano; forcella del cardano",
                ""),

    # ------------------------------------------------------ rotore e utensili
    "rotore": ("rotore", ROT,
                "albero con flange su cui si montano zappe o coltelli",
                "rotore; albero delle zappe; albero dei coltelli; asse; albero portautensili",
                "arvulu"),
    "rotore_completo": ("rotore completo di coltelli", ROT,
                "rotore della trinciatrice gia' montato con coltelli o mazze",
                "rotore completo; rotore con i coltelli; albero con le mazze",
                ""),
    "supporto_rotore": ("supporto rotore", ROT,
                "supporto laterale con cuscinetto del rotore della trinciatrice",
                "supporto rotore; supporto del cuscinetto; testata",
                ""),
    "mozzo_portalame": ("mozzo portalame", ROT,
                "mozzo su cui si imbullonano le lame del rasaerba",
                "mozzo lame; disco portalame; portalame",
                ""),
    "zappa": ("zappa per fresa", ROT,
                "utensile a L o C imbullonato sulle flange del rotore che lavora il terreno",
                "zappa; zappe; zappette; coltelli della fresa; lame della fresa; denti della fresa",
                "zappudda; zappi"),
    "mazza": ("mazza (martello) per trinciatrice", ROT,
                "utensile pesante snodato sul rotore che trincia erba e legna",
                "mazza; mazze; martello; martelli; coltello; coltelli della trincia",
                "mazza; marteddu"),
    "coltello_y": ("coltello a Y per trinciatrice", ROT,
                "coltello snodato a forma di Y (montato in coppia)",
                "coltello a Y; coltelli; lama a Y; coltellini; zappette della trincia",
                "cuteddu"),
    "coltello_dritto": ("coltello dritto per trinciatrice", ROT,
                "coltello snodato dritto",
                "coltello dritto; coltelli; lama; coltellino della trincia",
                "cuteddu"),
    "dente_erpice": ("coltello per erpice rotante", ROT,
                "dente verticale dell'erpice rotante, montato sul portadenti",
                "dente; denti; coltello; coltelli dell'erpice; lame; ferri",
                "denti"),
    "portadenti": ("portadenti erpice rotante", ROT,
                "supporto rotante su cui si fissano i due denti dell'erpice",
                "portadenti; porta coltelli; rotore dell'erpice; girante; trottola",
                ""),
    "lama_rasaerba": ("lama rasaerba", ROT,
                "lama rotante del trinciaerba",
                "lama; lame; coltello; lama del rasaerba",
                "cuteddu"),
    "controcoltello": ("controcoltello", ROT,
                "barra fissa dentro il cofano contro cui l'erba viene tagliata dai coltelli",
                "controcoltello; controlama; lama fissa; barra di taglio",
                ""),
    "dente_coltivatore": ("dente da coltivatore", ROT,
                "ancora/dente che lavora il terreno in profondita'",
                "dente; denti; ancora; ancore; vomere; zappa del coltivatore; molla",
                "denti"),
    "supporto_dente": ("supporto dente coltivatore", ROT,
                "staffa con morsetto che fissa il dente al telaio",
                "supporto dente; portadente; morsetto del dente; staffa del dente; attacco dente",
                ""),
    "puntale": ("puntale d'usura", ROT,
                "punta sostituibile avvitata sul dente, si consuma lavorando",
                "puntale; punta; punta del dente; scalpello; vomerino; punta d'usura",
                "punta"),
    "lama_spezzazolle": ("lama spezzazolle", ROT,
                "lama dietro ai denti che rompe le zolle",
                "spezzazolle; lama; livellatore; lama rompizolle",
                ""),
    "disco": ("disco", ROT,
                "disco dentato (smerlato) che taglia e rimescola il terreno",
                "disco; dischi; disco dentato; disco smerlato; padella",
                "discu"),
    "gruppo_disco": ("gruppo braccio con disco completo", ROT,
                "braccio portadisco completo di mozzo e disco",
                "disco completo; braccio con disco; gruppo disco; elemento disco",
                "discu"),
    "braccio_portadisco": ("braccio portadisco", ROT,
                "braccio piatto saldato che porta il mozzo del disco",
                "braccio del disco; portadisco; gamba del disco; supporto disco",
                ""),
    "tampone_gomma": ("tampone in gomma (elastomero)", ROT,
                "barra in gomma che fa da sospensione elastica ai bracci dei dischi",
                "gomma; gommini; tampone; elastomero; ammortizzatore in gomma; barra di gomma",
                "gomma"),
    "disco_laterale": ("disco laterale fresa", ROT,
                "disco montato sul fianco della fresa che taglia il bordo del terreno",
                "disco laterale; disco tagliabordo; disco rincalzatore; disco del fianco",
                "discu"),
    "supporto_disco_laterale": ("supporto disco laterale", ATT,
                "staffa e morsetto che fissano il disco laterale alla fresa",
                "supporto disco; staffa del disco; morsetto del disco; attacco disco laterale",
                ""),
    "pettine": ("pettine (rastrello) trinciatrice", ROT,
                "pettine posteriore dentro il cofano che trattiene il materiale da trinciare",
                "pettine; rastrello; griglia; denti del cofano; controdenti",
                ""),
    "lamiera_forata": ("lamiera forata", PRO,
                "lamiera forata di protezione",
                "lamiera forata; griglia; rete; lamiera bucata",
                "lamera"),

    # ------------------------------------------------------- rulli e ruote
    "rullo": ("rullo", RUL,
                "rullo posteriore che regola la profondita' e affina/compatta il terreno",
                "rullo; rullo posteriore; rullo compattatore; tamburo; cilindro",
                "rullu"),
    "rullo_packer": ("rullo packer", RUL,
                "rullo a denti/anelli dell'erpice rotante che compatta il terreno",
                "rullo packer; rullo dentato; rullo; rullo posteriore",
                "rullu"),
    "rullo_tubi": ("rullo a tubi", RUL,
                "rullo posteriore a tubi dell'erpice a dischi",
                "rullo a tubi; rullo a barre; rullo; rullo posteriore",
                "rullu"),
    "telaio_rullo": ("telaio portarullo", RUL,
                "telaio/bracci che collegano il rullo alla macchina",
                "telaio del rullo; bracci del rullo; portarullo; supporto rullo",
                ""),
    "supporto_rullo": ("supporto rullo", RUL,
                "piastra o staffa laterale che regge il rullo e ne regola l'altezza",
                "supporto rullo; piastra del rullo; staffa del rullo; fiancata del rullo; regolazione rullo",
                ""),
    "regolazione_rullo": ("regolazione rullo", RUL,
                "tubo/blocchetto/piastra per regolare l'altezza di lavoro del rullo",
                "regolazione rullo; registro del rullo; tubo di regolazione; blocchetto",
                ""),
    "raschiatore": ("raschiatore rullo", RUL,
                "lama che pulisce il rullo dalla terra attaccata",
                "raschiatore; raschietto; pulitore del rullo; lama del rullo",
                ""),
    "ruota": ("ruota", RUL,
                "ruota di appoggio del trinciaerba",
                "ruota; ruotino; ruota di appoggio; gommino",
                "rota"),
    "supporto_ruota": ("supporto ruota", RUL,
                "braccio o staffa che porta la ruota",
                "supporto ruota; braccio ruota; forcella della ruota",
                ""),
    "catenelle": ("catenelle di protezione", PRO,
                "tenda di catene davanti al cofano che trattiene sassi e detriti",
                "catene; catenelle; catena; tenda di catene; catenaccio di protezione; protezione a catene",
                "catina; catini"),

    # ------------------------------------------------------ telaio
    "telaio": ("telaio", TEL,
                "struttura portante saldata della macchina",
                "telaio; castello; struttura; carrello; scocca; ferro principale",
                "tilaiu"),
    "telaio_centrale": ("telaio centrale", TEL,
                "parte centrale del telaio dell'erpice pieghevole",
                "telaio centrale; parte centrale; carrello",
                "tilaiu"),
    "braccio": ("braccio pieghevole", TEL,
                "braccio laterale ripiegabile dell'erpice",
                "braccio; ala; braccio laterale; ala pieghevole",
                "brazzu"),
    "piastra_blocco_braccio": ("piastra blocco braccio", TEL,
                "piastra che blocca il braccio pieghevole in posizione",
                "blocco braccio; fermo dell'ala; piastra di fermo",
                ""),
    "cassone": ("cassone erpice rotante", TRA,
                "cassone a bagno d'olio che contiene gli ingranaggi dei rotori dell'erpice",
                "cassone; vasca; scatola degli ingranaggi; cassone dell'erpice; trave",
                ""),
    "coperchio_cassone": ("coperchio cassone", TRA,
                "coperchio superiore del cassone dell'erpice rotante",
                "coperchio; coperchio del cassone; tappo del cassone",
                ""),
    "alloggiamento": ("alloggiamento cuscinetti portadenti", TRA,
                "alloggiamento dei cuscinetti di un rotore portadenti nel cassone",
                "alloggiamento; sede cuscinetti; supporto rotore; campana",
                ""),
    "fiancata": ("fiancata", TEL,
                "piastra laterale del telaio che regge rotore, trasmissione e slitte",
                "fiancata; fianco; spalla; laterale; piastra laterale; sponda",
                ""),
    "cofano": ("cofano", PRO,
                "lamiera superiore che copre il rotore della trinciatrice",
                "cofano; carter; coperchio; lamiera sopra; carenatura; cuffia",
                ""),
    "cofano_posteriore": ("cofano posteriore", PRO,
                "lamiera posteriore incernierata della fresa che livella il terreno",
                "cofano posteriore; cofano; lamiera dietro; ala posteriore; sportello; portello; livellatore",
                ""),
    "barra_cerniera": ("barra cerniera cofano", PRO,
                "barra su cui e' incernierato il cofano posteriore",
                "cerniera; barra cerniera; asta della cerniera; snodo del cofano",
                ""),
    "copri_cerniera": ("copricerniera", PRO,
                "coperchio della cerniera del cofano",
                "copricerniera; coperchio della cerniera; protezione cerniera",
                ""),
    "angolare": ("angolare", TEL,
                "profilato a L di rinforzo o di attacco",
                "angolare; ferro a L; squadra; cantonale",
                ""),
    "rinforzo": ("rinforzo", TEL,
                "piatto o profilato di rinforzo del telaio",
                "rinforzo; ferro di rinforzo; piatto",
                ""),
    "tubo_quadro": ("tubo quadro", TEL,
                "tubo quadro del telaio su cui si fissano protezioni e attrezzature",
                "tubo quadro; trave; tubolare; barra quadra",
                "tubbu"),
    "barra_livellatrice": ("barra livellatrice", RUL,
                "barra (profilo a Z) dietro l'erpice che spiana il terreno",
                "barra livellatrice; livellatore; lama livellatrice; spianatore; tavola",
                ""),
    "regolazione_livellatrice": ("regolazione barra livellatrice", ATT,
                "manovella e supporti per regolare l'altezza della barra livellatrice",
                "manovella; regolazione livellatore; vite di regolazione; registro",
                ""),
    "sponda_mobile": ("sponda laterale mobile", PRO,
                "lamiera laterale flottante dell'erpice rotante che contiene la terra",
                "sponda; sponda laterale; paratia; lamiera laterale; parasassi",
                ""),
    "supporto_cilindro": ("supporto cilindro idraulico", IDR,
                "staffa/piastra su cui e' fissato il cilindro idraulico",
                "supporto pistone; staffa del pistone; attacco cilindro",
                ""),
    "gruppo_spostamento": ("staffa gruppo spostamento idraulico", ATT,
                "fiancata/staffa del gruppo di spostamento laterale idraulico",
                "spostamento laterale; staffa spostamento; fiancata idraulica; slitta dello spostamento",
                ""),

    # ------------------------------------------------------ protezioni
    "protezione": ("protezione", PRO,
                "lamiera o riparo di sicurezza (anteriore, laterale, CE)",
                "protezione; riparo; lamiera di protezione; carter; paraspruzzi; protezione CE",
                ""),
    "sponda_laterale": ("sponda laterale", PRO,
                "lamiera laterale regolabile che contiene la terra ai lati",
                "sponda; sponda laterale; paraterra; lamiera laterale; bandiera; deflettore",
                ""),
    "supporto_sponda": ("supporto sponda laterale", PRO,
                "tubo/piastra di fissaggio e regolazione della sponda laterale",
                "supporto sponda; tubo della sponda; regolazione sponda; attacco sponda",
                ""),
    "bandella_gomma": ("bandella in gomma", PRO,
                "striscia di gomma davanti/dietro il cofano che trattiene i detriti",
                "bandella; gomma; paraspruzzi; tenda in gomma; parasassi in gomma; flap",
                "gomma"),
    "carter_trasmissione": ("carter protezione trasmissione", PRO,
                "carter che copre pulegge e cinghie",
                "carter; carter cinghie; coperchio cinghie; protezione pulegge; cofano laterale",
                ""),

    # ------------------------------------------------- attacco, slitte, regolazioni
    "attacco_tre_punti": ("attacco a tre punti", ATT,
                "castelletto e staffe con cui la macchina si aggancia al sollevatore del trattore",
                "attacco tre punti; castelletto; torretta; piramide; attacco al trattore; staffe dei bracci",
                "attaccu"),
    "terzo_punto": ("terzo punto (tirante)", ATT,
                "tirante regolabile che collega il castelletto al trattore",
                "terzo punto; tirante; tirante regolabile; puntone; barra del terzo punto",
                "terzu puntu"),
    "spostamento_laterale": ("tubo scorrevole spostamento laterale", ATT,
                "tubo/asta su cui scorre la macchina per lo spostamento laterale",
                "tubo scorrevole; spostamento laterale; slitta; asta scorrevole; scorrimento",
                ""),
    "slitta": ("slitta laterale", ATT,
                "pattino laterale che appoggia a terra e regola la profondita' di lavoro",
                "slitta; slitte; pattino; pattini; sci; appoggio laterale",
                ""),
    "regolazione_slitta": ("regolazione slitta", ATT,
                "piastra forata o registro per regolare l'altezza della slitta",
                "regolazione slitta; registro slitta; piastra della slitta; regolatore profondita'",
                ""),
    "cavalletto": ("cavalletto di appoggio", ATT,
                "piede su cui la macchina sta in piedi quando e' staccata dal trattore",
                "cavalletto; piede; piedino; appoggio; stampella; puntello",
                "cavallettu"),
    "staffa_sollevamento": ("staffa di sollevamento", ATT,
                "staffa/gancio per sollevare la macchina o fissare la molla del cofano",
                "gancio; staffa; gancio di sollevamento; occhione",
                ""),
    "tirante_molla": ("tirante con molla cofano posteriore", ATT,
                "asta con molla che tiene premuto il cofano posteriore e ne regola l'apertura",
                "tirante; molla del cofano; asta con molla; ammortizzatore del cofano; registro del cofano",
                ""),
    "molla": ("molla", ATT,
                "molla elicoidale",
                "molla; molla a spirale; molla del cofano; mollone",
                "mudda"),
}

# (regex sul tipo, concetto) - vince la prima che corrisponde
REGOLE = [
    # minuteria specifica prima della generica
    (r"^mushroom head", "bullone_carrozzeria"),
    (r"^banjo bolt", "bullone_forato"),
    (r"^hex socket csk", "vite_svasata"),
    (r"^hex socket head", "vite_brugola"),
    (r"^handle", "maniglia"),
    (r"^u bolt", "cavallotto"),
    (r"^grease extention", "prolunga_ingrassatore"),
    (r"^hex bolt|^bolt$", "bullone"),
    (r"^nylock nut", "dado_autobloccante"),
    (r"^slotted round nut", "ghiera"),
    (r"^hex slotted check nut", "dado_corona"),
    (r"^hex nut", "dado"),
    (r"^spring washer", "rondella_grower"),
    (r"^(washer|washet|flat washer|rectangular washer|plain washer|lifting bracket washer)", "rondella"),
    (r"^linch pin", "spina_scatto"),
    (r"^r pin", "copiglia_r"),
    (r"^split pin", "coppiglia"),
    (r"^spring pin", "spina_elastica"),
    (r"^pto pin", "spina_fermo"),
    (r"^(pin lower three point|bottom link pin)", "perno_attacco"),
    (r"^hinge pin", "perno_cerniera"),
    (r"^center gear pin", "perno_ingranaggio"),
    (r"^pin$", "perno"),
    (r"^rivet", "rivetto"),
    (r"^(key|parallel key|gear box housing key)", "linguetta"),
    (r"^spring key", "molla"),
    (r"^end cap", "tappo_tubo"),
    (r"^(bush|bushing|rear teflon bush|sliding bush|guide bush)", "boccola"),
    (r"^(shim kit|sims)", "spessori"),
    (r"^sit lock", "calettatore"),
    (r"^manual box", "portadocumenti"),
    (r"^coupling", "giunto"),

    # cuscinetti e tenute
    (r"tapered roller bearing", "cuscinetto_conico"),
    (r"deep groove ball bearing", "cuscinetto_sfere"),
    (r"spherical roller bearing", "cuscinetto_orientabile"),
    (r"^(square flange bearing|ucf)", "supporto_flangiato"),
    (r"^(agri hub bearing|baa hub)", "mozzo_disco"),
    (r"^wheel width bearing|^wheel unit", "ruota"),
    (r"^oil seal", "paraolio"),
    (r"^o ring", "oring"),
    (r"^mechanical seal", "tenuta_meccanica"),
    (r"^blind seal", "tappo_cieco"),
    (r"^wiper seal", "raschiastelo"),
    (r"^dowty seal", "rondella_dowty"),
    (r"gasket|gaket", "guarnizione"),
    (r"^internal circlip", "seeger_interno"),
    (r"^external circlip", "seeger_esterno"),

    # lubrificazione
    (r"grease nipple", "ingrassatore"),
    (r"breathing plug", "tappo_sfiato"),
    (r"^oil level indicator", "spia_livello"),
    (r"^plug", "tappo_olio"),
    (r"^oil cup", "coppa_mozzo"),

    # idraulica
    (r"^hydraulic", "cilindro_idraulico"),
    (r"^plunger", "pistoncino"),
    (r"^hose pipe clamp", "fascetta_tubi"),
    (r"^hose pipe", "tubo_idraulico"),
    (r"^qrc", "innesto_rapido"),
    (r"^nipple male", "raccordo"),
    (r"^union male", "raccordo_t"),
    (r"^flow divider", "divisore_flusso"),
    (r"^cylinder (bracket|holding)", "supporto_cilindro"),
    (r"side (plate|bracket) hydraulic unit", "gruppo_spostamento"),

    # trasmissione
    (r"^gearbox extension", "rinvio_prolunga"),
    (r"^(gearbox|gear box) (body|body single speed)$|^gear box body", "corpo_scatola"),
    (r"^(gearbox|gear box) (support|bracket|base plate|pipe|tigthening|lifting lug|spacer)"
     r"|^gear box support|^base gearbox|^pipe support", "supporto_scatola"),
    (r"^(gearbox (front|back|top) cover|back cover|front cover|top cover"
     r"|intermediate shaft cover|drive shaft cover)", "coperchio_scatola"),
    (r"^gear cover", "coperchio_cascata"),
    (r"^(gearbox|gear box)( side shift| single speed| transmisson.*| sub)?$", "scatola_ingranaggi"),
    (r"^transmission housing", "carter_laterale"),
    (r"^transmisson$", "trasmissione_laterale"),
    (r"^transmission (shaft|pipe)", "albero_trasmissione"),
    (r"^blade drive shaft", "albero_portalama"),
    (r"^(drive shaft|pto drive shaft)", "albero_entrata"),
    (r"^intermediate shaft", "albero_intermedio"),
    (r"^(pinion|bevel pinion)", "pignone_conico"),
    (r"^bevel", "corona_conica"),
    (r"^center gear flange", "flangia_ingranaggio"),
    (r"^(upper|lower|central|center|side) gear", "ingranaggio_cascata"),
    (r"^(gear|change gear)$", "ingranaggio_cambio"),
    (r"^(hub|rotor hub) (gear side|oil cup side)$|^hub oil cup side|^rotor hub (gear|oil)", "mozzo_rotore"),
    (r"^hub housing", "supporto_mozzo"),
    (r"^hub shaft", "albero_mozzo"),
    (r"^dust cover", "parapolvere"),
    (r"^key free wheel", "ruota_libera"),
    (r"^pulley", "puleggia"),
    (r"^belt tension", "tendicinghia"),
    (r"^belt", "cinghia"),
    (r"^(pto guad|pto guard|pto shaft guard|shaft protection)", "protezione_cardano"),
    (r"^(pto hook|pto stand)", "supporto_cardano"),
    (r"^drive (cover|side cover)", "carter_trasmissione"),

    # rotore e utensili
    (r"^rotor (hammer|blade)", "rotore_completo"),
    (r"^rotor support", "supporto_rotore"),
    (r"^rotor hub$", "mozzo_portalame"),
    (r"^rotor", "rotore"),
    (r"^blade hammer", "mazza"),
    (r"^blade y", "coltello_y"),
    (r"^blade stright", "coltello_dritto"),
    (r"^blade spacer", "distanziale"),
    (r"^blade (lh|rh|c |ljf)", "zappa"),
    (r"^black blade", "dente_erpice"),
    (r"^blade holder", "portadenti"),
    (r"^blade$", "lama_rasaerba"),
    (r"^(cutter blade|double frame counter blade)", "controcoltello"),
    (r"^(tine|tyne)$", "dente_coltivatore"),
    (r"^tine bracket", "supporto_dente"),
    (r"^wearing point", "puntale"),
    (r"^clod breaking", "lama_spezzazolle"),
    (r"^side disc (lh|rh)$", "disco_laterale"),
    (r"^side disc", "supporto_disco_laterale"),
    (r"^disc( pcd notch)?$", "disco"),
    (r"^(front|rear) disc unit", "gruppo_disco"),
    (r"^(front|rear) disc flat", "braccio_portadisco"),
    (r"^rubber bar", "tampone_gomma"),
    (r"^rake", "pettine"),
    (r"^perfo", "lamiera_forata"),

    # rulli e ruote
    (r"^packer roller$", "rullo_packer"),
    (r"^(packer roller frame|tube roller frame|roller frame|rear roller frame"
     r"|disc roller (front |rear )?frame)", "telaio_rullo"),
    (r"^disc roller v bracket", "braccio_portadisco"),
    (r"^tube roller", "rullo_tubi"),
    (r"^roller (adjustment|blade adjustment)", "regolazione_rullo"),
    (r"^(roller (support|holding|inner|outer|connecting|fixing|lifting)|side plat packer|bush roller)",
     "supporto_rullo"),
    (r"^roller", "rullo"),
    (r"^scrapper", "raschiatore"),
    (r"^wheel", "supporto_ruota"),
    (r"^(chain link unit|chhain link|round steel link|rod chain link|chain holding angle)", "catenelle"),

    # telaio e carpenteria
    (r"^(frame|main frame)", "telaio"),
    (r"^center unit", "telaio_centrale"),
    (r"^(r )?arm$", "braccio"),
    (r"^arm lock", "piastra_blocco_braccio"),
    (r"^tank", "cassone"),
    (r"^lid", "coperchio_cassone"),
    (r"^(side|central) housing outer", "alloggiamento"),
    (r"^(side plate|internal plate)", "fiancata"),
    (r"^bonet", "cofano"),
    (r"^back hood", "cofano_posteriore"),
    (r"hinge bar", "barra_cerniera"),
    (r"^hinge cover", "copri_cerniera"),
    (r"^angle", "angolare"),
    (r"^reinforcement", "rinforzo"),
    (r"^sq pipe", "tubo_quadro"),
    (r"^section levelling bar", "barra_livellatrice"),
    (r"^(levelling bar crank|crank holding)", "regolazione_livellatrice"),
    (r"^mobile side", "sponda_mobile"),
    (r"^(support plate|cover plate)", "piastra"),

    # protezioni
    (r"^(protection|side protection|safety guard|lateral guard|front protection)", "protezione"),
    (r"^(side guard (support|clamping|top|bottom)|side guard pipe|pipe side gaurd)", "supporto_sponda"),
    (r"^side guard", "sponda_laterale"),
    (r"^rear support guard", "sponda_laterale"),
    (r"rubber flap", "bandella_gomma"),

    # attacco, slitte, regolazioni
    (r"^top link (cat|rod)", "terzo_punto"),
    (r"^(top mast|three point|tph base|top link bracket|bottom link bracket|side skid three point)",
     "attacco_tre_punti"),
    (r"^(sliding tube|rear sliding tube|sliding rod)", "spostamento_laterale"),
    (r"^(skid adjuster|depth skid spacer|skid spacer)", "regolazione_slitta"),
    (r"^(depth )?skid", "slitta"),
    (r"^parking stand", "cavalletto"),
    (r"^lifting bracket", "staffa_sollevamento"),
    (r"^(spring stud|support spring stud|bracket spring stud|bracket lifting spring"
     r"|adjustment pipe|adjustment rod|adujstment rod)", "tirante_molla"),
    (r"^spring", "molla"),
    (r"^spacer", "distanziale"),
]
