"""
Dati di arricchimento del catalogo SDF, scritti a mano (non generati da un
LLM a runtime): per ogni "tipo" di ricambio, i nomi con cui lo chiama un
cliente. Stessa tecnica del bot LANCER (bot_lancer/lancer_db/arricchimento.py),
adattata a SDF.

Perche' serve: le descrizioni SDF sono in italiano ma tecniche e spesso
generiche ("anello tenuta speciale", "pomolo", "tirante", "dispositivo
avviam."), mentre il cliente scrive "paraolio", "pomello", "filo
dell'acceleratore", "blocchetto accensione". Nei test dell'azienda
(dati/conversazioni_4.db) quasi tutti i pezzi "non trovati" erano a
catalogo, solo chiamati in un altro modo.

Struttura:
  CONCETTI  id -> (nome_it, sinonimi, siciliano, evoca)
            nome_it   nome tecnico chiaro, da mostrare come interpretazione
            sinonimi  come lo chiama il cliente (separati da ';')
            siciliano forme dialettali d'uso comune (DA VERIFICARE con
                      l'azienda: e' la parte piu' incerta)
            evoca     parole di contesto (a cosa serve / dove sta): pesano
                      meno dei nomi, come il nome della tavola
  REGOLE    lista ordinata (regex sul "tipo", id concetto): vince la PRIMA
            che corrisponde, quindi le specifiche stanno sopra le generiche.
  MINUTERIA concetti di bulloneria/carpenteria generica: se il pezzo e'
            trovato SOLO per il nome della tavola, conta la meta' (una vite
            della tavola "RADIATORE" non deve pareggiare il radiatore).
  CONTESTI  (regex sul contesto "gruppo / sottogruppo / tavola", parole):
            parole aggiunte al contesto di tutte le righe di quelle tavole
            (es. "P.T.O." -> presa di forza, cardano, attrezzi).

Il "tipo" e' la descrizione senza misure, sigle e lato (vedi
ricerca.tipo_di): "anello tenuta speciale 25 x 32 x 7" -> "anello tenuta
speciale". Il catalogo SDF cresce a ogni modello scaricato: i tipi nuovi
che non corrispondono a nessuna regola vengono comunque cercati con la
loro descrizione originale, e si possono elencare con
  ./venv/Scripts/python.exe -m fornitori.sdf.ricerca --senza-regola
per aggiungere la regola qui.
"""

CONCETTI = {
    # ------------------------------------------------------- bulloneria
    "bullone": ("bullone", "vite; bullone esagonale; vite testa esagonale; vite con dado", "bulluni", ""),
    "vite": ("vite", "bullone; vite a brugola; vitina; viteria", "viti", ""),
    "dado": ("dado", "dado esagonale; dado autobloccante; dado con la plastica; madrevite; bullone femmina", "dadu", ""),
    "rondella": ("rondella", "rosetta; ranella; rondella piana; grower; rondella elastica; rondella spaccata", "rundedda; rudedda", ""),
    "guarnizione_rame": ("guarnizione di rame", "rondella di rame; rosetta di rame; ranella di rame; guarnizione rame", "", ""),
    "prigioniero": ("prigioniero", "vite prigioniera; perno filettato; colonnetta; tirante filettato", "", ""),
    "grano": ("grano", "grano filettato; vite senza testa; brugola senza testa", "", ""),
    "spina": ("spina", "spina elastica; spinotto; spina cilindrica; spina di centraggio; perno", "", ""),
    "copiglia": ("copiglia", "coppiglia; molletta; spina a molla; fermo del perno", "cupigghia", ""),
    "rivetto": ("rivetto", "ribattino; chiodo da ribattere", "", ""),
    "fascetta": ("fascetta", "fascetta stringitubo; fascetta del tubo; collare; fascetta di plastica; morsetto", "", ""),
    "morsetto": ("morsetto", "fascetta; collare; clip; morsetto del tubo", "", ""),
    "cavallotto": ("cavallotto", "bullone a U; staffa a U; cavaliere", "", ""),
    "distanziale": ("distanziale", "spessore; distanziatore; bussola; tubetto distanziale", "", ""),
    "rasamento": ("rasamento", "spessore; spessori; lamierino; rondella di registro; anello di registro", "", ""),
    "anello_spallamento": ("anello di spallamento", "spessore; rasamento; anello di registro; distanziale; fermo", "", ""),
    "anello_elastico": ("anello elastico (seeger)", "seeger; fermo; fermi; anello di fermo; anello di sicurezza; circlip; molletta di fermo", "", ""),
    "linguetta": ("linguetta", "chiavetta; chiavella; chiave dell'albero; tassello", "", ""),
    "ingrassatore": ("ingrassatore", "nipplo; nipplo del grasso; ingrassatore a sfera; punto di ingrassaggio", "", "grasso lubrificazione"),
    "tappo": ("tappo", "tappo di scarico; tappo di chiusura; tappo filettato; tappino; coperchio", "tappu", ""),
    "passacavo": ("passacavo", "passafilo; gommino passacavo; anello passacavo", "", ""),
    "staffa": ("staffa", "supporto; staffetta; squadretta; piastrina; mensola; attacco", "", ""),
    "supporto": ("supporto", "staffa; sostegno; supportino; attacco; piastra", "", ""),
    "piastra": ("piastra", "piastrina; lamiera; piatto di fissaggio; lamierino", "", ""),
    "molletta": ("molletta", "fermaglio; clip; graffetta; molla piccola", "", ""),
    "perno": ("perno", "spinotto; asse; perno di snodo; perno di articolazione", "pernu", ""),
    "coperchio": ("coperchio", "coperchietto; calotta; cappellotto; copertura; tappo", "cuperchiu", ""),
    "ghiera": ("ghiera", "dado tondo; ghiera di bloccaggio; dado a intagli", "", ""),
    "fermo": ("fermo", "blocco; arresto; fermo di bloccaggio", "", ""),
    "asta": ("asta", "astina; bacchetta; asta di comando; tirante", "", ""),
    "tassello": ("tassello", "tassello elastico; tampone; gommino; silentblock", "", ""),
    "gancio": ("gancio", "gancetto; uncino", "", ""),
    "puntone": ("puntone", "tirante; asta di spinta", "", ""),

    # ------------------------------------------------ tenute e cuscinetti
    "anello_tenuta": ("anello di tenuta (paraolio / o-ring)",
                      "paraolio; paraoli; o-ring; oring; anello or; guarnizione; guarnizioni; tenuta; tenute; "
                      "anellino di gomma; anello di gomma; guarnizione dell'albero; kit guarnizioni",
                      "paraogghiu", ""),
    "paraolio": ("paraolio", "anello di tenuta; paraoli; guarnizione dell'albero; tenuta; anello tenuta",
                 "paraogghiu", ""),
    "guarnizione": ("guarnizione", "guarnizioni; tenuta; guarnizione di carta; guarnizione piana; o-ring; anello di tenuta",
                    "uarnizioni", ""),
    "guarnizione_testata": ("guarnizione della testata", "guarnizione testa; guarnizione testa motore; guarnizione della testa",
                            "a uarnizioni dâ testa", "motore testata"),
    "serie_guarnizioni": ("serie guarnizioni (kit)", "kit guarnizioni; kit di guarnizioni; kit tenute; kit revisione; kit riparazione",
                          "", ""),
    "serie_anelli_tenuta": ("serie anelli di tenuta (kit)",
                            "kit guarnizioni; serie guarnizioni; kit paraoli; kit tenute; kit o-ring; kit revisione; kit riparazione",
                            "", ""),
    "serie_revisione": ("serie per revisione (kit)", "kit revisione; kit riparazione; kit guarnizioni; serie guarnizioni", "", ""),
    "soffietto": ("soffietto", "cuffia; parapolvere; protezione in gomma", "", ""),
    "gommino": ("gommino", "tampone in gomma; antivibrante; silentblock; supporto in gomma", "", ""),
    "silentblock": ("silentblock", "supporto elastico; antivibrante; tampone in gomma; gommino; tassello elastico; supporto in gomma",
                    "", ""),
    "tampone": ("tampone in gomma", "gommino; paracolpi; antivibrante; silentblock", "", ""),
    # "reggispinta" NON sta qui ma in CONTESTI (tavole COMANDO DELLA FRIZIONE):
    # qui lo darebbe a tutti i cuscinetti del trattore
    "cuscinetto": ("cuscinetto", "cuscinetti; cuscinetto a sfere; cuscinetto a rulli", "cuscinettu", ""),
    "gabbia_rullini": ("gabbia a rullini", "cuscinetto a rullini; rullini; gabbietta; astuccio a rullini", "", ""),
    "boccola": ("boccola", "bronzina; bussola; boccola in bronzo; cuscinetto a strisciamento", "buccula", ""),
    "semibronzina_banco": ("semibronzina di banco", "bronzine di banco; bronzine albero motore; cuscinetti di banco; bronzine",
                           "", "motore"),
    "semibronzina_biella": ("semibronzina di biella", "bronzine di biella; bronzine biella; cuscinetti di biella; bronzine",
                            "", "motore"),
    "bronzina": ("bronzina", "boccola; bussola; semibronzina; cuscinetto", "", ""),
    "rondella_spallamento": ("rondella di spallamento (rasamento albero)",
                             "rasamenti; spessori; mezzelune; semianelli; rondelle reggispinta", "", ""),
    "ralla": ("ralla", "rondella reggispinta; rasamento; spessore; ralla reggispinta", "", ""),
    "sfera": ("sfera", "pallina; biglia; sferetta", "", ""),
    "rullino": ("rullino", "rullini; rullo", "", ""),

    # ---------------------------------------------------------- motore
    "monoblocco": ("monoblocco (basamento)", "basamento; blocco motore; carter motore", "", "motore"),
    "testata": ("testata", "testa motore; testa dei cilindri; testata motore", "a testa du muturi", "motore"),
    "gruppo_pistone_canna": ("gruppo pistone e canna", "canna; canne; canne cilindro; camicia; camicie; pistone e canna; "
                             "kit pistone canna; cilindri del motore", "", "motore"),
    "canna": ("canna del cilindro", "canna; canne; camicia; camicie; cilindro del motore", "", "motore"),
    "pistone_motore": ("pistone del motore", "pistone; pistoni; stantuffo", "pistuni", "motore"),
    "pistone": ("pistone", "pistoni; stantuffo; pistoncino", "pistuni", ""),
    "pistone_freno": ("pistone del freno", "pistone freno; pistoncino freno; stantuffo del freno", "", "freni"),
    "serie_fasce": ("serie fasce elastiche", "fasce; fasce elastiche; segmenti; anelli del pistone; fasce del pistone",
                    "", "motore pistone"),
    "fascia_elastica": ("fascia elastica", "fascia; segmento; anello del pistone", "", ""),
    "biella": ("biella", "bielle", "", ""),
    "albero_motore": ("albero motore", "albero a gomiti; albero a manovelle; albero centrale del motore",
                      "l'arvulu du muturi", "motore"),
    "albero_camme": ("albero a camme", "albero della distribuzione; albero a boccioli; asse a camme", "", "motore distribuzione"),
    "valvola_motore": ("valvola del motore", "valvole; valvola di aspirazione; valvola di scarico; valvole motore",
                       "", "testata motore"),
    "guida_valvola": ("guida valvola", "guidavalvola; guide valvole", "", "testata"),
    "sede_valvola": ("sede valvola", "sedi valvola; seggio valvola", "", "testata"),
    "bilanciere": ("bilanciere", "bilancieri; leva della valvola", "", "testata motore"),
    "punteria": ("punteria", "punterie; spingivalvola; bicchierino", "", ""),
    "volano": ("volano motore", "volano; volano del motore", "", "motore frizione"),
    "corona": ("corona dentata", "corona; corona del volano; ingranaggio grande; dentatura", "", ""),
    "coppa_olio": ("coppa dell'olio", "coppa olio; carter olio; coppa motore; vasca dell'olio", "", "motore"),
    "pompa_olio_motore": ("pompa dell'olio motore", "pompa olio; pompa lubrificazione", "", "motore lubrificazione"),
    "asta_livello": ("asta livello olio", "astina dell'olio; astina livello; asta dell'olio; bacchetta dell'olio", "", "motore"),
    "filtro_olio_motore": ("filtro olio motore", "filtro olio; filtro dell'olio; filtrino olio; cartuccia olio",
                           "u filtru di l'ogghiu", "motore olio"),
    "filtro_olio_idraulico": ("filtro olio idraulico", "filtro idraulico; filtro olio cambio; filtro olio trasmissione; "
                              "filtro olio sollevatore; cartuccia filtro olio; filtro olio", "", "idraulico olio"),
    "filtro_aria": ("filtro aria", "filtro dell'aria; cartuccia aria; elemento filtro aria; filtro a secco",
                    "u filtru di l'aria", "motore aspirazione"),
    "filtro_aria_cabina": ("filtro aria cabina", "filtro abitacolo; filtro antipolline; filtro carboni attivi; filtro cabina",
                           "", "cabina"),
    "filtro_gasolio": ("filtro gasolio", "filtro nafta; filtro carburante; filtro combustibile; prefiltro; "
                       "filtro separatore acqua; cartuccia gasolio", "u filtru dâ nafta", "alimentazione gasolio nafta carburante"),
    "filtro": ("filtro", "filtri; filtrino; retina; cartuccia", "filtru", ""),
    "pompa_iniezione": ("pompa d'iniezione", "pompa iniezione; pompa gasolio; pompa nafta; pompa del gasolio; "
                        "pompa ad alta pressione", "a pompa dâ nafta", "motore alimentazione"),
    "pompante": ("pompante (elemento pompa iniezione)", "elemento pompante", "", ""),
    "pompa_alimentazione": ("pompa di alimentazione (pompetta AC)",
                            "pompetta; pompetta ac; pompetta gasolio; pompetta alimentazione; pompetta a mano; pompa ac; "
                            "pompa di adescamento; pompetta nafta; pompetta del gasolio",
                            "a pumpetta", "ac gasolio nafta carburante alimentazione"),
    "iniettore": ("iniettore", "iniettori; polverizzatore; portapolverizzatore; spruzzatore; ugello iniezione",
                  "u spruzzaturi", "motore iniezione"),
    "polverizzatore": ("polverizzatore", "ugello; spruzzatore; iniettore; punta dell'iniettore", "", "iniezione"),
    "turbo": ("turbocompressore", "turbo; turbina", "a turbina", "motore"),
    "intercooler": ("intercooler", "radiatore aria; radiatore del turbo; scambiatore aria", "", ""),
    "collettore_scarico": ("collettore di scarico", "collettore scarico; collettore dei gas; collettore dei fumi",
                           "", "motore scarico"),
    "collettore_aspirazione": ("collettore di aspirazione", "collettore aspirazione; collettore aria", "", "motore"),
    "collettore": ("collettore", "collettore", "", ""),
    "marmitta": ("marmitta", "silenziatore; scappamento; tubo di scarico", "u silenziaturi", "scarico"),
    "tubo_scarico": ("tubo di scarico", "scappamento; tubo della marmitta; tubo marmitta; gomito di scarico; tubo dei fumi",
                     "u tubu du scaricu", "scarico"),
    "catalizzatore": ("catalizzatore / filtro antiparticolato", "filtro antiparticolato; dpf; catalizzatore; fap",
                      "", "scarico"),
    "termostato": ("termostato", "termostato acqua; valvola termostatica; valvola della temperatura",
                   "u dermustatu", "raffreddamento acqua temperatura"),
    "pompa_acqua": ("pompa dell'acqua", "pompa acqua; pompa del radiatore; pompa di raffreddamento; pompetta acqua",
                    "a pompa di l'acqua", "raffreddamento motore"),
    "radiatore_acqua": ("radiatore acqua", "radiatore; radiatore del motore; radiatore di raffreddamento",
                        "u ragiaturi", "raffreddamento"),
    "radiatore_olio": ("radiatore olio", "radiatore dell'olio; scambiatore olio; radiatorino olio; radiatore", "", ""),
    "radiatore_gasolio": ("radiatore gasolio", "radiatore carburante; scambiatore gasolio; radiatore", "", ""),
    "radiatore_clima": ("condensatore aria condizionata", "radiatore aria condizionata; condensatore clima; radiatore clima",
                        "", "cabina"),
    "radiatore": ("radiatore", "radiatore; scambiatore", "u ragiaturi", ""),
    "ventola": ("ventola", "ventola; elica; ventilatore; pala; ventola di raffreddamento", "a ventula", ""),
    "ventola_cabina": ("ventola cabina", "ventilatore cabina; ventola riscaldamento; motorino ventilazione", "", "cabina"),
    "convogliatore": ("convogliatore", "convogliatore aria; cuffia ventola; deflettore; carenatura della ventola", "", ""),
    "cinghia": ("cinghia", "cinghia alternatore; cinghia ventola; cinghia pompa acqua; cinghia trapezoidale; cinghia poly v",
                "a cinta", ""),
    "tendicinghia": ("tendicinghia", "galoppino; tenditore; rullo tendicinghia; puleggia tendicinghia", "", "cinghia"),
    "puleggia": ("puleggia", "puleggia; ruota della cinghia; puleggia albero motore", "", "cinghia"),
    "candeletta": ("candeletta", "candeletta; termoavviatore; resistenza preriscaldo; candela di preriscaldo; candela",
                   "", "avviamento preriscaldo"),

    # ---------------------------------------------------- elettrico
    "alternatore": ("alternatore", "dinamo; generatore; quello che ricarica la batteria", "a dinamu", ""),
    "motorino_avviamento": ("motorino di avviamento", "motorino; motorino avviamento; starter; avviamento",
                            "u muturinu", "avviamento"),
    "blocchetto_accensione": ("blocchetto di accensione (commutatore a chiave)",
                              "blocchetto accensione; blocchetto avviamento; quadro di accensione; quadro accensione; "
                              "quadro chiave; chiave di accensione; commutatore di avviamento; commutatore a chiave; "
                              "interruttore a chiave; blocchetto chiave; accensione; avviamento",
                              "", "chiave accendere accensione avviamento quadro"),
    "chiave_accensione": ("chiave di accensione", "chiave; chiavetta; chiave del quadro; chiave per quadro; chiave di avviamento",
                          "", "accensione"),
    "interruttore": ("interruttore", "pulsante; tasto; commutatore; bottone; interruttore", "", ""),
    "pulsante": ("pulsante", "bottone; interruttore; tasto", "", ""),
    "deviatore": ("deviatore luci (devioluci)", "devioluci; devio luci; devioguida; leva delle luci; leva frecce; "
                  "comando luci; deviatore; commutatore luci", "", "luci frecce"),
    "rele": ("rele", "rele; relay; teleruttore", "", "impianto elettrico"),
    "fusibile": ("fusibile", "fusibili; valvola; valvolina", "", "impianto elettrico"),
    "portafusibili": ("portafusibili", "scatola fusibili; porta fusibili; centralina fusibili", "", ""),
    "lampadina": ("lampadina", "lampada; lampadine; bulbo della luce", "", "luci"),
    "faro": ("faro", "fari; fanale; proiettore; faro anteriore; luce anteriore", "", "luci"),
    "faro_lavoro": ("faro di lavoro", "fari da lavoro; faro posteriore; faretto; luce di lavoro", "", "luci"),
    "fanalino": ("fanalino", "fanale; luce posteriore; stop; luce stop; freccia; frecce; luce di posizione; fanalino posteriore",
                 "", "luci"),
    "vetro_fanale": ("vetro del fanale", "plastica del fanale; gemma; vetrino; copertura fanale", "", "luci"),
    "lampeggiante": ("lampeggiante", "girofaro; luce rotante; lampada rotante; lampeggiatore", "", "luci"),
    "intermittenza": ("rele intermittenza", "intermittenza frecce; rele frecce; intermittente", "", "luci frecce"),
    "catadiottro": ("catarifrangente", "catadiottro; riflettore; catarifrangente", "", ""),
    "clacson": ("clacson", "tromba; avvisatore acustico; cicalino", "", ""),
    "cavo_elettrico": ("cavo elettrico", "filo elettrico; filo; fili; cavo; cavetto; cavo della batteria; cavo massa",
                       "u filu", "impianto elettrico batteria"),
    "cablaggio": ("cablaggio", "impianto elettrico; cablaggio; fascio cavi; fili; fili elettrici", "", ""),
    "batteria": ("batteria", "accumulatore", "a batteria", ""),
    "sensore_pressione": ("sensore di pressione", "bulbo; bulbo olio; bulbo pressione; sensore pressione olio; "
                          "pressostato; trasmettitore pressione", "", ""),
    "sensore_temperatura": ("sensore di temperatura", "bulbo; bulbo temperatura; bulbo acqua; sonda temperatura; "
                            "trasmettitore temperatura; termocontatto", "", "temperatura"),
    "sensore_livello": ("sensore di livello (galleggiante)", "galleggiante; galleggiante gasolio; indicatore di livello; "
                        "sonda livello; livello carburante; livello gasolio", "", "serbatoio livello"),
    "sensore_posizione": ("sensore di posizione (potenziometro)", "potenziometro; sensore pedale; sensore acceleratore; "
                          "potenziometro acceleratore", "", "pedale acceleratore"),
    "sensore_velocita": ("sensore di velocita", "sensore giri; pick up; sensore contagiri", "", ""),
    "sensore": ("sensore", "sonda; trasmettitore; bulbo", "", ""),
    "centralina": ("centralina elettronica", "centralina; ecu; computer; scheda elettronica", "", ""),
    "strumento": ("strumento del cruscotto", "contagiri; contaore; quadro strumenti; strumentazione; tachimetro; "
                  "contachilometri; cruscotto", "", ""),
    "cruscotto": ("cruscotto", "plancia; quadro strumenti; cruscotto", "", ""),
    "spia": ("spia", "spia luminosa; lampada spia", "", ""),
    "presa_corrente": ("presa di corrente", "presa elettrica; presa rimorchio; presa 7 poli; presa accendisigari", "", ""),
    "tergicristallo": ("tergicristallo", "spazzola tergicristallo; motorino tergicristallo; tergi; spazzola", "", ""),

    # -------------------------------------------- frizione, cambio, trasmissione
    "frizione_completa": ("frizione completa", "frizione; kit frizione; frizione centrale; frizione principale; "
                          "gruppo frizione; frizione motore", "a frizioni", "centrale principale"),
    "disco_frizione": ("disco frizione", "disco della frizione; ferodo; ferodo frizione; kit frizione", "u discu dâ frizioni", ""),
    "spingidisco": ("spingidisco", "plato; piatto frizione; piatto spingidisco", "u chiattu dâ frizioni", "frizione"),
    "frizione_idraulica": ("frizione idraulica / multidisco", "frizione pto; pacco dischi; frizione multidisco", "", ""),
    "disco": ("disco", "dischi; lamella; ferodo", "", ""),
    "controdisco": ("controdisco", "disco in acciaio; lamella; controdischi", "", ""),
    "disco_freno": ("disco freno", "dischi freno; ferodi freno; ferodo; disco del freno", "", "freni"),
    "nastro_freno": ("nastro del freno", "nastro freno; ganascia; ferodo freno a nastro", "", "freni"),
    "ganascia": ("ganascia del freno", "ceppo; ganasce; ceppi", "", "freni"),
    "tamburo_freno": ("tamburo del freno", "tamburo", "", "freni"),
    "pompa_freni": ("pompa dei freni", "pompa freno; cilindro maestro freni; pompetta freni", "", "freni"),
    "leva_cambio": ("leva del cambio", "leva cambio; leva marce; leva delle marce", "", "cambio marce"),
    "pomolo": ("pomolo (pomello)", "pomello; pomo; manopola; pomello della leva; pomello del cambio; pomello leva",
               "", "leva"),
    "impugnatura": ("impugnatura", "manopola; pomello; pomolo; maniglia", "", "leva"),
    "maniglia": ("maniglia", "manopola; impugnatura", "", ""),
    "leva": ("leva", "levetta; leverismo; braccio di comando", "", ""),
    "pedale": ("pedale", "pedali; pedaliera", "", ""),
    "pedale_acceleratore": ("pedale acceleratore", "acceleratore a pedale; pedale del gas", "", "acceleratore"),
    "tirante": ("tirante (asta o filo di comando)", "filo; cavo; filo di comando; cavo di comando; asta; bacchetta",
                "u filu", ""),
    "cavo": ("cavo di comando", "filo; cavo flessibile; flessibile; cavo bowden; cavetto; filo di comando",
             "u filu", ""),
    "leva_freno_mano": ("leva freno a mano", "freno a mano; leva stazionamento; freno di stazionamento", "", "freni"),
    "dente_arresto": ("dente d'arresto", "nottolino; cricchetto; arpione", "", ""),
    "settore_dentato": ("settore dentato", "cremagliera; settore; dentiera", "", ""),
    "arresto": ("arresto (fermo)", "fermo; blocco; battuta", "", ""),
    "ingranaggio": ("ingranaggio", "ingranaggi; ruota dentata; pignone; marcia; ingranaggio doppio", "u ngranaggiu", ""),
    "pignone": ("pignone", "ingranaggio; ingranaggio piccolo", "", ""),
    "coppia_conica": ("coppia conica", "corona e pignone; corona conica; pignone conico; coppia del ponte",
                      "", "ponte differenziale"),
    "satellite": ("satellite", "satelliti; ingranaggio satellite; ingranaggio del differenziale", "", "differenziale riduttore"),
    "planetario": ("planetario", "planetari; ingranaggio del differenziale", "", "differenziale"),
    "portasatellite": ("portasatellite", "porta satelliti; portasatelliti; supporto satelliti", "", "riduttore ponte"),
    "scatola_cambio": ("scatola del cambio", "cambio; carter del cambio; scatola cambio", "a scatula du cambiu", "cambio"),
    "scatola_riduttore": ("scatola del riduttore", "riduttore; riduttore finale; carter del riduttore", "", "ponte"),
    "regolatore": ("regolatore", "regolatore di giri; regolatore di tensione", "", ""),
    "scatola_differenziale": ("scatola del differenziale", "differenziale; cassa differenziale; scatola differenziale", "", ""),
    "sincronizzatore": ("sincronizzatore", "sincro; anello sincronizzatore", "u sincru", "cambio"),
    "forcella": ("forcella", "forchetta; forcellino", "", ""),
    "albero_primario": ("albero primario", "primario; albero entrata cambio; albero della frizione", "", "cambio"),
    "albero_secondario": ("albero secondario", "secondario; albero uscita cambio", "", "cambio"),
    "albero_pto": ("albero della presa di forza (PTO)",
                   "albero pto; albero presa di forza; presa di forza; pto; codolo; codolo pto; meccia; attacco del cardano; "
                   "albero scanalato; mozzicone; albero attrezzi", "", "attrezzi cardano presa forza potenza"),
    "albero_trasmissione": ("albero di trasmissione", "cardano; albero cardanico; albero del 4x4; albero della doppia trazione; "
                            "albero centrale; albero sotto il trattore", "", "trasmissione doppia trazione 4x4"),
    "semiasse": ("semiasse", "semiassi; albero ruota; asse ruota; albero della ruota", "", ""),
    "albero": ("albero", "asse; alberino", "l'arvulu", ""),
    "piantone": ("piantone dello sterzo", "piantone; colonna sterzo; albero sterzo; albero del volante", "", "sterzo volante"),
    "manicotto": ("manicotto", "giunto; manicotto scanalato; manicotto di accoppiamento", "", ""),
    "manicotto_gomma": ("manicotto in gomma", "tubo in gomma; tubo del radiatore; manicotto radiatore; manicotto acqua", "", ""),
    "giunto": ("giunto", "giunto cardanico; crociera; snodo; giunto omocinetico; giunto elastico", "", ""),
    "crociera": ("crociera", "crociera del cardano; giunto cardanico", "", ""),
    "mozzo": ("mozzo", "mozzo ruota; flangia", "", ""),
    "flangia": ("flangia", "flangetta; piatto", "", ""),

    # -------------------------------------------- idraulica e sollevatore
    "pompa_idraulica": ("pompa idraulica", "pompa oleodinamica; pompa olio idraulico; pompa del sollevatore; "
                        "pompa dello sterzo; pompa ad ingranaggi", "", "idraulico"),
    "pompa": ("pompa", "pompetta", "a pompa", ""),
    "distributore": ("distributore idraulico", "distributore; valvola distributore; comando idraulico; distributore ausiliario",
                     "", "idraulico"),
    "innesto_rapido": ("innesto rapido", "prese idrauliche; presa idraulica; attacco rapido; attacchi rapidi; innesti rapidi; "
                       "innesto femmina; presa olio; presa dell'olio", "", "idraulico rapido olio"),
    "cilindro": ("cilindro (idraulico)", "cilindretto; cilindro idraulico; pistone idraulico; martinetto; cilindro ricevitore",
                 "", ""),
    "stelo": ("stelo", "asta del pistone; stelo del cilindro", "", ""),
    "valvola": ("valvola", "valvolina; valvola di sicurezza; valvola di massima", "", ""),
    "elettrovalvola": ("elettrovalvola", "valvola elettrica; solenoide", "", ""),
    "bobina": ("bobina", "bobina elettrovalvola; solenoide", "", ""),
    "tubo": ("tubo", "tubazione; tubo olio; tubetto; tubo idraulico; tubo flessibile; flessibile", "u tubu", ""),
    "raccordo": ("raccordo", "bocchettone; raccordo idraulico; attacco del tubo; nipplo; raccordo a occhio; banjo; "
                 "bullone forato; riduzione; adattatore", "", ""),
    "leva_sollevamento": ("braccio del sollevatore", "braccio sollevatore; bracci del sollevatore; leva sollevatore; "
                          "braccio di sollevamento; leva di sollevamento", "", "sollevatore sollevamento"),
    "braccio": ("braccio", "bracci", "", ""),
    "molla": ("molla", "molle; molla di richiamo; molla elicoidale", "a mudda", ""),
    "molla_gas": ("molla a gas", "pistoncino a gas; ammortizzatore a gas; molla cofano", "", ""),
    "tirante_3p": ("tirante dell'attacco a tre punti", "terzo punto; puntone; tirante verticale; tiranti del sollevatore",
                   "", "sollevatore attacco"),
    "stabilizzatore": ("stabilizzatore", "catena stabilizzatrice; tirante laterale; stabilizzatori", "", "sollevatore"),
    "catena": ("catena", "catene", "", ""),
    "rotula": ("rotula", "snodo sferico; testa a snodo; uniball", "", ""),
    "gancio_traino": ("gancio di traino", "gancio; gancio traino; gancio rimorchio; gancio posteriore; attacco rimorchio",
                      "", "rimorchio"),
    "barra_traino": ("barra di traino", "barra oscillante; barra traino; timone", "", "rimorchio"),
    "gancio_automatico": ("gancio automatico", "ganci automatici; gancio rapido; gancio del braccio", "", "sollevatore"),

    # ------------------------------------------------------------ sterzo
    "idroguida": ("idroguida", "guida idrostatica; servosterzo; orbitrol; scatola sterzo", "", "sterzo"),
    "volante": ("volante", "volante di guida; sterzo", "", ""),
    "snodo": ("snodo", "testina; snodo sferico; testina sterzo; tirante sterzo", "", ""),

    # ------------------------------------------------------- carrozzeria
    "cofano": ("cofano", "cofano motore", "", ""),
    "fianchetto": ("fianchetto del cofano", "fianchetto; fiancata; pannello laterale", "", "cofano"),
    "griglia": ("griglia", "calandra; mascherina; retina", "", ""),
    "parafango": ("parafango", "parafanghi", "", ""),
    "pedana": ("pedana", "gradino; predellino", "", ""),
    "scaletta": ("scaletta", "scala; gradini; predellino", "", ""),
    "sedile": ("sedile", "sellino; seggiolino", "", ""),
    "molleggio_sedile": ("molleggio del sedile", "sospensione sedile; ammortizzatore sedile", "", "sedile"),
    "specchio": ("specchietto retrovisore", "specchietto; specchio; retrovisore", "", ""),
    "vetro": ("vetro della cabina", "cristallo; vetro; parabrezza; lunotto; finestrino", "", "cabina"),
    "targhetta": ("targhetta / adesivo", "adesivo; adesivi; scritta; scritte; decalcomania; decalcomanie; etichetta; "
                  "stemma; logo", "", ""),
    "serbatoio": ("serbatoio", "tanica", "", ""),
    "serbatoio_carburante": ("serbatoio del gasolio", "serbatoio carburante; serbatoio nafta; serbatoio gasolio", "", "gasolio"),
    "vaschetta": ("vaschetta", "vaschetta di espansione; vasetto; serbatoio acqua", "", ""),
    "zavorra": ("zavorra", "pesi; contrappesi; zavorre; masse", "", ""),
    "pneumatico": ("pneumatico", "gomma; gomme; copertone", "", "ruota"),
    "camera_aria": ("camera d'aria", "camera", "", "ruota"),
    "cerchio": ("cerchio", "cerchione; cerchio ruota", "", "ruota"),
    "telaio": ("telaio", "chassis; struttura", "", ""),
    "roll_bar": ("arco di sicurezza (roll-bar)", "arco di sicurezza; roll bar; rollbar; telaio di protezione", "", ""),
    "protezione": ("protezione", "riparo; carter; copertura; lamiera di protezione", "", ""),
    "tappeto": ("tappeto", "tappetino; insonorizzante; moquette", "", "cabina"),
    "cintura": ("cintura di sicurezza", "cintura", "", ""),
    "serratura": ("serratura", "chiusura; chiavistello", "", ""),

    # ------------------------------------------------------------ cingoli
    "catenaria": ("catenaria del cingolo", "cingolo; catena del cingolo; cingoli", "", "cingolo"),
    "maglia_catena": ("maglia del cingolo", "maglia; maglie; anello della catena", "", "cingolo"),
    "suola": ("suola del cingolo", "pattino; soletta; suole", "", "cingolo"),
    "rullo": ("rullo del cingolo", "rullo; rulli; rullo sostegno; rullo appoggio", "", "cingolo"),
    "ruota_cingolo": ("ruota del cingolo", "ruota motrice; ruota tendicingolo; ruota dentata", "", "cingolo"),
}


# (regex sul tipo, concetto): vince la PRIMA che corrisponde
REGOLE = [
    # tenute (prima di "anello" e "guarnizione" generici)
    (r"^serie anelli tenuta", "serie_anelli_tenuta"),
    (r"^serie guarnizioni", "serie_guarnizioni"),
    (r"^serie per revisione|^kit ricambi", "serie_revisione"),
    (r"^serie fasce", "serie_fasce"),
    (r"^serie spazzole", "motorino_avviamento"),
    (r"^anello tenuta|^anello in gomma", "anello_tenuta"),
    (r"^paraolio", "paraolio"),
    (r"^guarnizione testata", "guarnizione_testata"),
    (r"^guarnizione di rame", "guarnizione_rame"),
    (r"^guarnizione", "guarnizione"),
    (r"^anello elastico", "anello_elastico"),
    (r"^anello spallamento|^spallamento", "anello_spallamento"),
    (r"^anello passacavo|^passafilo", "passacavo"),
    (r"^anello spingidisco", "spingidisco"),
    (r"^anello di frizione", "anello_spallamento"),
    (r"^soffietto|^cuffia|^parapolvere", "soffietto"),
    (r"^silentblock", "silentblock"),
    (r"^tampone", "tampone"),
    (r"^gommino", "gommino"),
    # cuscinetti e boccole
    (r"^gabbia rullini", "gabbia_rullini"),
    (r"^cuscinetto", "cuscinetto"),
    (r"^semibronzina banco", "semibronzina_banco"),
    (r"^semibronzina biella", "semibronzina_biella"),
    (r"^semibronzina|^bronzina", "bronzina"),
    (r"^boccola|^bussola", "boccola"),
    (r"^rondella di spall", "rondella_spallamento"),
    (r"^ralla", "ralla"),
    (r"^sfera", "sfera"),
    (r"^rullino", "rullino"),
    # bulloneria
    (r"^bullone", "bullone"),
    (r"^vite", "vite"),
    (r"^dado", "dado"),
    (r"^rondella|^rosetta", "rondella"),
    (r"^prigioniero|^colonnetta|^colonna$", "prigioniero"),
    (r"^grano", "grano"),
    (r"^spina|^spinotto", "spina"),
    (r"^copiglia|^coppiglia", "copiglia"),
    (r"^rivetto|^ribattino|^chiodo", "rivetto"),
    (r"^fascetta", "fascetta"),
    (r"^morsetto|^collare", "morsetto"),
    (r"^cavallotto", "cavallotto"),
    (r"^distanziale", "distanziale"),
    (r"^rasamento|^spessore|^lamierino", "rasamento"),
    (r"^linguetta|^chiavetta", "linguetta"),
    (r"^ingrassatore", "ingrassatore"),
    (r"^tappo", "tappo"),
    (r"^staffa|^staffetta|^squadretta|^angolare", "staffa"),
    (r"^supporto sedile", "sedile"),
    (r"^supporto|^supportino", "supporto"),
    (r"^piastra|^piastrina", "piastra"),
    (r"^molletta|^graffetta", "molletta"),
    (r"^perno|^pernetto", "perno"),
    (r"^coperchi|^calotta|^cappellotto", "coperchio"),
    (r"^ghiera", "ghiera"),
    (r"^fermo", "fermo"),
    (r"^asta$", "asta"),
    (r"^tassello", "tassello"),
    (r"^puntone", "puntone"),
    (r"^chiave$|^chiavetta", "linguetta"),
    (r"^fascia$", "fascetta"),
    (r"^retina", "filtro"),
    (r"^serie accessori", "serie_revisione"),
    (r"^scatola cambio", "scatola_cambio"),
    (r"^scatola riduttore", "scatola_riduttore"),
    (r"^regolatore", "regolatore"),
    (r"^settore$", "settore_dentato"),
    (r"^guida sedile|^bracciolo|^supporto sedile", "sedile"),
    (r"^traversa", "telaio"),
    # motore
    (r"^monoblocco", "monoblocco"),
    (r"^testa motore", "testata"),
    (r"^gruppo pistone canna", "gruppo_pistone_canna"),
    (r"^cilindro motore|^canna|^camicia", "canna"),
    (r"^pistone completo", "pistone_motore"),
    (r"^pistone freno", "pistone_freno"),
    (r"^pistone|^pistoncino|^stantuffo", "pistone"),
    (r"^fascia elastica", "fascia_elastica"),
    (r"^biella", "biella"),
    (r"^albero motore", "albero_motore"),
    (r"^albero boccioli", "albero_camme"),
    (r"^valvola (aspirazione|scarico)", "valvola_motore"),
    (r"^guida valvola", "guida_valvola"),
    (r"^sede valvola", "sede_valvola"),
    (r"^bilanciere", "bilanciere"),
    (r"^punteria", "punteria"),
    (r"^volano", "volano"),
    (r"^corona conica", "coppia_conica"),
    (r"^corona", "corona"),
    (r"^coppa olio", "coppa_olio"),
    (r"^pompa olio", "pompa_olio_motore"),
    (r"^asta livello", "asta_livello"),
    (r"^filtro olio motore", "filtro_olio_motore"),
    (r"^elemento filtrante olio|^filtro olio|^filtro ft", "filtro_olio_idraulico"),
    (r"^filtro aria cabina|^filtro carboni", "filtro_aria_cabina"),
    (r"^filtro aria|^elemento filtrante aria", "filtro_aria"),
    (r"combustibile|^prefiltro", "filtro_gasolio"),
    (r"^filtro dpf|^catalizzatore", "catalizzatore"),
    (r"^filtro", "filtro"),
    (r"^pompa iniezione", "pompa_iniezione"),
    (r"^pompante", "pompante"),
    (r"^pompa alimentazione|^adescatore", "pompa_alimentazione"),
    (r"^iniettore|^portapolverizzatore", "iniettore"),
    (r"^polverizzatore|^ugello", "polverizzatore"),
    (r"^turbo", "turbo"),
    (r"^intercooler", "intercooler"),
    (r"^collettore scarico", "collettore_scarico"),
    (r"^collettore aspir", "collettore_aspirazione"),
    (r"^collettore", "collettore"),
    (r"^marmitta|^silenziatore", "marmitta"),
    (r"^tubo di scarico|^gomito di scarico", "tubo_scarico"),
    (r"^termostato aria", "radiatore_clima"),
    (r"^termostato", "termostato"),
    (r"^pompa acqua", "pompa_acqua"),
    (r"^radiatore acqua", "radiatore_acqua"),
    (r"^radiatore olio", "radiatore_olio"),
    (r"^radiatore gasolio", "radiatore_gasolio"),
    (r"^radiatore aria|^condensatore aria|^condizionatore", "radiatore_clima"),
    (r"^radiatore", "radiatore"),
    (r"^ventola cabina|^corpo ventilatore|^girante", "ventola_cabina"),
    (r"^ventola", "ventola"),
    (r"^convogliatore|^deflettore", "convogliatore"),
    (r"^cinghia", "cinghia"),
    (r"^galoppino|^tenditore$|^tenditore kpl", "tendicinghia"),
    (r"^puleggia", "puleggia"),
    (r"^termoavviatore|^candela|^candeletta", "candeletta"),
    # elettrico
    (r"^alternatore", "alternatore"),
    (r"^motorino avviamento|^indotto|^portaspazzole", "motorino_avviamento"),
    (r"^dispositivo avviam", "blocchetto_accensione"),
    (r"^chiave per quadro", "chiave_accensione"),
    (r"^deviatore", "deviatore"),
    (r"^interruttore", "interruttore"),
    (r"^pulsante", "pulsante"),
    (r"^rele", "rele"),
    (r"^porta fusibili", "portafusibili"),
    (r"^fusibile", "fusibile"),
    (r"^lampadina", "lampadina"),
    (r"^fari di lavoro", "faro_lavoro"),
    (r"^faro|^fanale|^parabola", "faro"),
    (r"^fanalino", "fanalino"),
    (r"^vetro fanale|^vetrino", "vetro_fanale"),
    (r"^lampeggiatore|^girofaro", "lampeggiante"),
    (r"^intermittente", "intermittenza"),
    (r"^catadiottro|^riflettore", "catadiottro"),
    (r"^avvisatore|^cicalino", "clacson"),
    (r"^cavo elettrico", "cavo_elettrico"),
    (r"^impianto elettrico", "cablaggio"),
    (r"^batteria|^accumulatore$", "batteria"),
    (r"^sensore di pressione|^pressostato", "sensore_pressione"),
    (r"^sensore di temperatura|^indicatore temperatura", "sensore_temperatura"),
    (r"^sensore di livello|^indicatore livello|^galleggiante", "sensore_livello"),
    (r"^sensore di posizione|^potenziometro", "sensore_posizione"),
    (r"^sensore velocita", "sensore_velocita"),
    (r"^sensore", "sensore"),
    (r"^centralina", "centralina"),
    (r"^cronotachigirometro|^strumento|^portastrumenti", "strumento"),
    (r"^cruscotto", "cruscotto"),
    (r"^spia", "spia"),
    (r"^presa corrente", "presa_corrente"),
    (r"tergicristallo", "tergicristallo"),
    # frizione, cambio, trasmissione
    (r"^frizione completa", "frizione_completa"),
    (r"^frizione (idr|multidisco)", "frizione_idraulica"),
    (r"^disco frizione", "disco_frizione"),
    (r"^spingidisco", "spingidisco"),
    (r"^disco freno", "disco_freno"),
    (r"^controdisco", "controdisco"),
    (r"^disco$", "disco"),
    (r"^nastro freno", "nastro_freno"),
    (r"^ceppo", "ganascia"),
    (r"^tamburo freno", "tamburo_freno"),
    (r"^pompa freni", "pompa_freni"),
    (r"^leva cambio", "leva_cambio"),
    (r"^leva freno mano", "leva_freno_mano"),
    (r"^leva sollevamento", "leva_sollevamento"),
    (r"^pomolo", "pomolo"),
    (r"^impugnatura|^manopola", "impugnatura"),
    (r"^maniglia", "maniglia"),
    (r"^leva|^levetta", "leva"),
    (r"^pedale acceleratore", "pedale_acceleratore"),
    (r"^pedale|^pedalino", "pedale"),
    (r"^tirante (inferiore|superiore|terzo|verticale|regolabile|cat)|^terzo punto", "tirante_3p"),
    (r"^tirante", "tirante"),
    (r"^cavo", "cavo"),
    (r"^dente di arresto|^nottolino", "dente_arresto"),
    (r"^settore dentato", "settore_dentato"),
    (r"^arresto", "arresto"),
    (r"^ingranaggio|^ruota dentata", "ingranaggio"),
    (r"^pignone conico|^coppia conica", "coppia_conica"),
    (r"^pignone", "pignone"),
    (r"^satellite", "satellite"),
    (r"^planetario", "planetario"),
    (r"^portasatellite", "portasatellite"),
    (r"^scatola diff", "scatola_differenziale"),
    (r"^sincronizzatore", "sincronizzatore"),
    (r"^forcella", "forcella"),
    (r"^albero primario", "albero_primario"),
    (r"^albero secondario", "albero_secondario"),
    (r"^albero presa potenza", "albero_pto"),
    (r"^albero trasmissione", "albero_trasmissione"),
    (r"^albero ruota|^semiasse", "semiasse"),
    (r"^albero sterzo|^colonna sterzo", "piantone"),
    (r"^albero|^alberino", "albero"),
    (r"^manicotto in gomma", "manicotto_gomma"),
    (r"^manicotto per (terzo|tirante|stabilizzatore)", "tirante_3p"),
    (r"^manicotto", "manicotto"),
    (r"^giunto", "giunto"),
    (r"^crociera", "crociera"),
    (r"^mozzo", "mozzo"),
    (r"^flangia|^flangetta", "flangia"),
    # idraulica, sollevatore, sterzo
    (r"^pompa idraulica|^pompa cc|^corpo pompa", "pompa_idraulica"),
    (r"^pompetta acqua tergicristallo", "tergicristallo"),
    (r"^pompa", "pompa"),
    (r"^distributore", "distributore"),
    (r"^innesto", "innesto_rapido"),
    (r"^cilindro|^martinetto", "cilindro"),
    (r"^stelo", "stelo"),
    (r"^elettrovalvola", "elettrovalvola"),
    (r"^bobina", "bobina"),
    (r"^valvola|^corpo valvola", "valvola"),
    (r"^tubo|^tubetto|^tubazione", "tubo"),
    (r"^raccordo|^bocchettone|^riduzione|^adattatore|^testina", "raccordo"),
    (r"^braccio (destro|sinistro)$|^braccio$|^braccio kit", "braccio"),
    (r"^molla gas", "molla_gas"),
    (r"^molleggio sedile|^sedile molleggiato", "molleggio_sedile"),
    (r"^molla", "molla"),
    (r"^stabilizzatore|^asta filettata stabilizzatore|^tenditore per stabilizzatore", "stabilizzatore"),
    (r"^catena", "catena"),
    (r"^rotula", "rotula"),
    (r"^gancio di traino", "gancio_traino"),
    (r"^barra di traino", "barra_traino"),
    (r"^gancio (automatico|braccio|terzo)", "gancio_automatico"),
    (r"^gancio", "gancio"),
    (r"^idroguida", "idroguida"),
    (r"^volante", "volante"),
    (r"^snodo", "snodo"),
    # carrozzeria
    (r"^cofano|^frontale per cofano|^fascia frontale", "cofano"),
    (r"^fianco", "fianchetto"),
    (r"^griglia|^rete", "griglia"),
    (r"^parafango", "parafango"),
    (r"^pedana", "pedana"),
    (r"^scaletta", "scaletta"),
    (r"^sedile", "sedile"),
    (r"^specchi", "specchio"),
    (r"^vetro|^parabrezza|^lunotto|^finestrino", "vetro"),
    (r"^targhetta|^simbolo|^etichett|^adesivo", "targhetta"),
    (r"^serbatoio carburante", "serbatoio_carburante"),
    (r"^serbatoio", "serbatoio"),
    (r"^vaschetta", "vaschetta"),
    (r"^zavorra|^massa", "zavorra"),
    (r"^pneumatico", "pneumatico"),
    (r"^camera aria", "camera_aria"),
    (r"^cerchio", "cerchio"),
    (r"^telaio di sicurezza", "roll_bar"),
    (r"^telaio", "telaio"),
    (r"^riparo|^protezione|^carter|^copertura|^lamiera di protezione", "protezione"),
    (r"^tappeto|^insonorizzante", "tappeto"),
    (r"^cintura", "cintura"),
    (r"^serratura|^chiusura|^chiavistello", "serratura"),
    # cingoli
    (r"^catenaria", "catenaria"),
    (r"^maglia catena|^elemento di giunz", "maglia_catena"),
    (r"^suola|^pattino", "suola"),
    (r"^rullo", "rullo"),
    (r"^ruota (motrice|tendicingolo)|^ruota$", "ruota_cingolo"),
]


# bulloneria e carpenteria generica: vedi docstring
MINUTERIA = {
    "bullone", "vite", "dado", "rondella", "guarnizione_rame", "prigioniero", "grano", "spina", "copiglia",
    "rivetto", "fascetta", "morsetto", "cavallotto", "distanziale", "rasamento", "anello_spallamento",
    "linguetta", "tappo", "passacavo", "staffa", "supporto", "piastra", "molletta",
}


# (regex sul contesto "GRUPPO / SOTTOGRUPPO / TAVOLA", parole aggiunte al contesto)
CONTESTI = [
    (r"P\.\s?T\.\s?O|PRESA DI POTENZA", "presa di forza presa di potenza pto cardano attrezzi"),
    (r"S\.\s?A\.\s?C|SOLLEVA", "sollevatore alzata bracci"),
    (r"ORGAN[OI] SENSIBIL", "sforzo controllato controllo sforzo sollevatore"),
    (r"IDROGUIDA|GUIDA IDROSTATICA|STERZO", "sterzo guida"),
    (r"4WD|PONTE ANTERIORE|TRAZIONE ANTERIORE", "4x4 doppia trazione trazione anteriore"),
    (r"ALBERO DI TRASMISSIONE", "cardano albero cardanico sotto trattore ponte anteriore posteriore"),
    (r"BLOCCHETTO (DI )?(ACCENSIONE|AVVIAMENTO)", "accensione chiave quadro commutatore avviamento accendere"),
    (r"MARCE|CAMBIO|RIDUTTORE|GAMME", "cambio marce"),
    (r"INVERSORE", "inversore avanti indietro retromarcia"),
    (r"ACCELERATORE", "gas acceleratore"),
    (r"RAFFREDDAMENTO|RADIATOR|VENTOL", "raffreddamento radiatore"),
    (r"ALIMENTAZIONE|CARBURANTE|COMBUSTIBILE|GALLEGGIANTE", "gasolio nafta carburante"),
    (r"FRENO A MANO", "freno a mano stazionamento"),
    (r"FRIZIONE DELLO STERZO|CINGOL|CATENARIA", "cingolo cingolato"),
    (r"DEVIOGUIDA|DEVIATORE", "devioluci frecce luci"),
    (r"INNEST|PRESE POSTERIORI|DISTRIBUTOR", "prese idrauliche attacchi rapidi"),
    (r"TARGHETT|LETTERING|SIMBOL", "adesivi scritte"),
    (r"ALBERO (FRIZIONE|ENTRATA)", "albero frizione primario"),
    (r"COMANDO DELLA FRIZIONE|COMANDI FRIZIONE", "pedale frizione reggispinta spingidisco"),
    (r"FANAL|FARI|ILLUMINAZIONE|LUCE", "luci"),
    (r"BATTERIA", "batteria"),
    (r"MOTORE|BASAMENTO|TESTA DEI CILINDRI|CILINDRO - PISTONE", "motore"),
    (r"PONTE POSTERIORE|ASSALE POSTERIORE|SEMIASSI", "ponte posteriore"),
]
